services:
  java_app:
    container_name: java_app
    build: .
    ports:
      - "8080:8080"
# Evitar llamar al comando build cada vez que haya cambios en el .jar
    volumes:
      - ./target:/app
      - ./env.properties:/app/env.properties
    depends_on:
      - java_db
  java_db:
    container_name: java_db
    image: postgres
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_volumen:/var/lib/postgresql/data
volumes:
  postgres_volumen:

