services:
  java_app:
    container_name: java_app
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./target/codemail-0.0.1-SNAPSHOT.jar:/app/app_java.jar
    depends_on:
      - java_db
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      LLAVE_ENCRIPTAR: ${LLAVE_ENCRIPTAR}
  java_db:
    container_name: java_db
    image: postgres
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_volumen:/var/lib/postgresql/data
volumes:
  postgres_volumen:

