services:
  java_app:
    container_name: java_app
    build: .
    ports:
      - "8080:8080"
    links:
      - java_db
  java_db:
    container_name: java_db
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: euler
      POSTGRES_PASSWORD: password
      POSTGRES_DB: codemail


