spring:
  datasource:
    url: jdbc:postgresql://java_db:5432/codemail
    username: euler
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update